exports.LOGIN_REQUEST = 'LOGIN_REQUEST';
exports.LOGIN_FAILURE = 'LOGIN_FAILURE';
exports.LOGIN_SUCCESS = 'LOGIN_SUCCESS';
exports.LOGOUT_REQUEST = 'LOGOUT_REQUEST';
exports.LOGOUT_FAILURE = 'LOGOUT_FAILURE';
exports.LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
