
/**
 * CONSUMER'S ACTION TYPES
 */

exports.CONSUMER_INDEX_LOADING = 'CONSUMER_INDEX_LOADING';
exports.CONSUMER_INDEX_SUCCESS = 'CONSUMER_INDEX_SUCCESS';
exports.CONSUMER_INDEX_ERROR = 'CONSUMER_INDEX_ERROR';

exports.CONSUMER_UPDATE_LOADING = 'CONSUMER_UPDATE_LOADING';
exports.CONSUMER_UPDATE_SUCCESS = 'CONSUMER_UPDATE_SUCCESS';
exports.CONSUMER_UPDATE_ERROR = 'CONSUMER_UPDATE_ERROR';

exports.CONSUMER_CREATE_LOADING = 'CONSUMER_CREATE_LOADING';
exports.CONSUMER_CREATE_SUCCESS = 'CONSUMER_CREATE_SUCCESS';
exports.CONSUMER_CREATE_ERROR = 'CONSUMER_CREATE_ERROR';

exports.CONSUMER_DELETE_LOADING = 'CONSUMER_DELETE_LOADING';
exports.CONSUMER_DELETE_SUCCESS = 'CONSUMER_DELETE_SUCCESS';
exports.CONSUMER_DELETE_ERROR = 'CONSUMER_DELETE_ERROR';

exports.CONSUMER_SET_ITEM_TO_DELETE = 'CONSUMER_SET_ITEM_TO_DELETE';

exports.CONSUMER_SET_EDIT_MODE = 'CONSUMER_SET_EDIT_MODE';
exports.CONSUMER_RESET_EDIT_MODE = 'CONSUMER_RESET_EDIT_MODE';

exports.CONSUMER_SET_ADD_MODE = 'CONSUMER_SET_ADD_MODE';
