exports.MAP_VEHICLE_BOX_CLICK = 'MAP_VEHICLE_BOX_CLICK';

exports.MAP_REMOVE_FROM_ACTIVE_BUS_REQUEST = 'MAP_REMOVE_FROM_ACTIVE_BUS_REQUEST';
exports.MAP_REMOVE_FROM_ACTIVE_BUS_ERROR = 'MAP_REMOVE_FROM_ACTIVE_BUS_ERROR';
exports.MAP_REMOVE_FROM_ACTIVE_BUS_SUCCESS = 'MAP_REMOVE_FROM_ACTIVE_BUS_SUCCESS';

exports.MAP_ADD_TO_ACTIVE_BUS_REQUEST = 'MAP_ADD_TO_ACTIVE_BUS_REQUEST';
exports.MAP_ADD_TO_ACTIVE_BUS_ERROR = 'MAP_ADD_TO_ACTIVE_BUS_ERROR';
exports.MAP_ADD_TO_ACTIVE_BUS_SUCCESS = 'MAP_ADD_TO_ACTIVE_BUS_SUCCESS';

exports.MAP_HIGHLIGHT_MARKER = 'MAP_HIGHLIGHT_MARKER';
exports.MAP_HIGHLIGHT_MARKER_OFF = 'MAP_HIGHLIGHT_MARKER_OFF';

exports.DIRECTIONS_LOAD_REQUEST= 'DIRECTIONS_LOAD_REQUEST';
exports.DIRECTIONS_LOAD_FAILURE= 'DIRECTIONS_LOAD_FAILURE';
exports.DIRECTIONS_LOAD_SUCCESS = 'DIRECTIONS_LOAD_SUCCESS';

exports.DIRECTIONS_HIDE = 'DIRECTIONS_HIDE';

exports.MARKER_CLICK_ERROR = 'MARKER_CLICK_ERROR';

exports.MAP_CLUSTER_MOUSEOVER = 'MAP_CLUSTER_MOUSEOVER';
exports.MAP_CLUSTER_INFO_CLOSE = 'MAP_CLUSTER_INFO_CLOSE';
exports.MAP_SAVE_CLUSTERS = 'MAP_SAVE_CLUSTERS';
exports.MAP_ZOOM_CHANGED = 'MAP_ZOOM_CHANGED';

exports.MAP_OPEN_MARKER_INFO = 'MAP_OPEN_MARKER_INFO';
exports.MAP_CLOSE_MARKER_INFO = 'MAP_CLOSE_MARKER_INFO';

exports.MAP_SET_CENTER = 'MAP_SET_CENTER';
