exports.MAP_VEHICLE_BOX_CLICK = 'MAP_VEHICLE_BOX_CLICK';

exports.MAP_REMOVE_FROM_ACTIVE_BUS_REQUEST = 'MAP_REMOVE_FROM_ACTIVE_BUS_REQUEST';
exports.MAP_REMOVE_FROM_ACTIVE_BUS_ERROR = 'MAP_REMOVE_FROM_ACTIVE_BUS_ERROR';
exports.MAP_REMOVE_FROM_ACTIVE_BUS_SUCCESS = 'MAP_REMOVE_FROM_ACTIVE_BUS_SUCCESS';

exports.MAP_ADD_TO_ACTIVE_BUS_REQUEST = 'MAP_ADD_TO_ACTIVE_BUS_REQUEST';
exports.MAP_ADD_TO_ACTIVE_BUS_ERROR = 'MAP_ADD_TO_ACTIVE_BUS_ERROR';
exports.MAP_ADD_TO_ACTIVE_BUS_SUCCESS = 'MAP_ADD_TO_ACTIVE_BUS_SUCCESS';

exports.MAP_HIGHLIGHT_MARKER = 'MAP_HIGHLIGHT_MARKER';
exports.MAP_HIGHLIGHT_MARKER_OFF = 'MAP_HIGHLIGHT_MARKER_OFF';

exports.DIRECTIONS_DISPLAY = 'DIRECTIONS_LOAD';
