exports.FILTER_UPDATE = 'FILTER_UPDATE';
exports.FILTER_VEHICLE_UPDATE = 'FILTER_VEHICLE_UPDATE';
exports.FILTER_SET_ALL_NEEDS = 'FILTER_SET_ALL_NEEDS';
exports.FILTER_SET_ALL_VEHICLES = 'FILTER_SET_ALL_VEHICLES';
