exports.SETTINGS_LOAD_REQUEST = 'SETTINGS_LOAD_REQUEST';
exports.SETTINGS_LOAD_FAILURE = 'SETTINGS_LOAD_FAILURE';
exports.SETTINGS_LOAD_SUCCESS = 'SETTINGS_LOAD_SUCCESS';
exports.SETTINGS_UPDATE = 'SETTINGS_UPDATE';
