exports.SETTINGS_FORM_UPDATE_REQUEST = 'SETTINGS_FORM_UPDATE_REQUEST';
exports.SETTINGS_FORM_UPDATE_FAILURE = 'SETTINGS_FORM_UPDATE_FAILURE';
exports.SETTINGS_FORM_UPDATE_SUCCESS = 'SETTINGS_FORM_UPDATE_SUCCESS';
