
/**
 * USER'S ACTION TYPES
 */

exports.USER_RESET_PWD_LOADING = 'USER_RESET_PWD_LOADING';
exports.USER_RESET_PWD_SUCCESS = 'USER_RESET_PWD_SUCCESS';
exports.USER_RESET_PWD_ERROR = 'USER_RESET_PWD_ERROR';
