
/**
 * USER'S ACTION TYPES
 */

exports.USER_INDEX_LOADING = 'USER_INDEX_LOADING';
exports.USER_INDEX_SUCCESS = 'USER_INDEX_SUCCESS';
exports.USER_INDEX_ERROR = 'USER_INDEX_ERROR';

exports.USER_UPDATE_ROLE_LOADING = 'USER_UPDATE_ROLE_LOADING';
exports.USER_UPDATE_ROLE_SUCCESS = 'USER_UPDATE_ROLE_SUCCESS';
exports.USER_UPDATE_ROLE_ERROR = 'USER_UPDATE_ROLE_ERROR';

exports.USER_RESET_PWD_LOADING = 'USER_RESET_PWD_LOADING';
exports.USER_RESET_PWD_SUCCESS = 'USER_RESET_PWD_SUCCESS';
exports.USER_RESET_PWD_ERROR = 'USER_RESET_PWD_ERROR';

exports.USER_CREATE_LOADING = 'USER_CREATE_LOADING';
exports.USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
exports.USER_CREATE_ERROR = 'USER_CREATE_ERROR';

exports.USER_DELETE_LOADING = 'USER_DELETE_LOADING';
exports.USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
exports.USER_DELETE_ERROR = 'USER_DELETE_ERROR';

exports.USER_SET_ITEM_TO_DELETE = 'USER_SET_ITEM_TO_DELETE';
exports.USER_SET_ITEM_TO_RESET = 'USER_SET_ITEM_TO_RESET';

exports.USER_SET_EDIT_MODE = 'USER_SET_EDIT_MODE';
exports.USER_RESET_EDIT_MODE = 'USER_RESET_EDIT_MODE';

exports.USER_SET_ADD_MODE = 'USER_SET_ADD_MODE';
