exports.DIRECTIONS_LOAD_REQUEST= 'DIRECTIONS_LOAD_REQUEST';
exports.DIRECTIONS_LOAD_FAILURE= 'DIRECTIONS_LOAD_FAILURE';
exports.DIRECTIONS_LOAD_SUCCESS = 'DIRECTIONS_LOAD_SUCCESS';

exports.DIRECTIONS_HIDE = 'DIRECTIONS_HIDE';

exports.OPTIMIZE_ROUTE_REQUEST = 'OPTIMIZE_ROUTE_REQUEST';
exports.OPTIMIZE_ROUTE_FAILURE = 'OPTIMIZE_ROUTE_FAILURE';
exports.OPTIMIZE_ROUTE_SUCCESS = 'OPTIMIZE_ROUTE_SUCCESS';

exports.SAVE_ROUTE_TIME_REQUEST = 'SAVE_ROUTE_TIME_REQUEST';
exports.SAVE_ROUTE_TIME_FAILURE = 'SAVE_ROUTE_TIME_FAILURE';
exports.SAVE_ROUTE_TIME_SUCCESS = 'SAVE_ROUTE_TIME_SUCCESS';
