exports.WPT_ADD_REQUEST = 'WPT_ADD_REQUEST'
exports.WPT_ADD_SUCCESS = 'WPT_ADD_SUCCESS'
exports.WPT_ADD_FAILURE = 'WPT_ADD_FAILURE'

exports.WPT_EDIT_REQUEST = 'WPT_EDIT_REQUEST'
exports.WPT_EDIT_SUCCESS = 'WPT_EDIT_SUCCESS'
exports.WPT_EDIT_FAILURE = 'WPT_EDIT_FAILURE'

exports.WPT_FORMS_CHANGED = 'WPT_FORMS_CHANGED'
